### ISSUE TITLE
RN 0.32

### ISSUE THREAD

**Issue by michaelswe** [futurice/pepperoni-app-kit#111]
I suppose not all are using RN >= 0.30, so a PR might be bad. I thought we could gather the needed tweaks in an issue until Pepperoni is ready to go RN 0.32. Everything seems to work fine, but the title rendering.
- Title rendering
  As of RN 0.30 (I think), the header function for NavigationCardStack is named **renderHeader** instead of **renderOverlay**. Just change this in the render-function in NavigationView.js
- Title height
  The fix for the navigation bar height (ba9a1ef) now needs to be undone. This seems to be fixed in RN instead. For now, just remark "marginTop: APP_BAR_HEIGHT" in the sceneContainer-style in NavigationView.js.

**Comment by Jazznight** [comment]
I made [another fork](https://github.com/Jazznight/rx_react_native_starter_kit) for upgrading the starter kit to RN 0.34 include all you mentioned.

e.g. 
1. I replaced the effect handler from redux-loop/thunk/promise to redux-observable
2. Locker theme is not working after upgrade to RN 0.34.

**Comment by krivachy** [comment]
Thanks for the info needed to upgrade. We'll get on this soon. A PR is appreciated if you have one! 🍕 🚀

**Comment by tino-junge** [comment]
We've recently upgraded to RN 0.35, so I suppose we can close this issue here now
