### ISSUE TITLE
Application PepperoniAppTemplatehas not been registered

### ISSUE THREAD

**Issue by GeoffreyPlitt** [futurice/pepperoni-app-kit#118]
I cloned, npm-installed, and did 'react-native run-andriod'.

I get the following error:
```
Application PepperoniAppTemplate has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent
```

Please advise, thanks.

**Comment by PalleZingmark** [comment]
This might be related to the terminal still being hooked to a process in another React project. 
Try the following:

1. Shut the Terminal spawned by React Native.
2. Shut down XCode completely (may not be necessary).
3. Re-open everything and re-run.

**Comment by GeoffreyPlitt** [comment]
That worked, thanks.
