### ISSUE TITLE
iOS 10 build fails

### ISSUE THREAD

**Issue by asashay** [futurice/pepperoni-app-kit#120]
Hi.

Have been developing ios app for the past few monthes already. Now, after new iOS release, can not build and launch it.

What is proper way to upgrade the kit to be compatible with iOS 10?

Thanks.

**Comment by timdoege** [comment]
The following works for me for iOS 10 / Xcode 8:

1. Upgrade to react native 0.34 (https://facebook.github.io/react-native/docs/upgrading.html)

Run this from a terminal in your pepperoni app root folder:
`$ npm install --save react-native@0.34`

In order for this, you also need to upgrade React by running
`$ npm install --save react@15.3.0`

Finally, upgrade your project templates by running

`$ react-native upgrade`

The latter will ask you for every file that gets overwritten - just answer "Y" for every file.


2. Update Pods:
Run
`$ (cd ios; pod repo update; pod install)`

3. Revert some of the changes from the upgrade process.
Assuming your project is under version control: Check all the diffs before comitting - usually you just want to revert the changes to ".gitignore".

4. Adapt a few changes for RN 0.30 (and above) for the navigation
Just follow the two steps here:
https://github.com/futurice/pepperoni-app-kit/issues/111

5. In Xcode 8 (might not be nescessary for RN 0.34+)
Open the ios project in Xcode 8 and build it. If you encounter two compile errors, apply the changes mentioned here:
https://github.com/facebook/react-native/issues/8584 (scroll down to "TimBroddin commented on 30 Jul")

6. Clean node_modules
For good measure, remove the node_modules folder
`$ rm -Rf node_modules/`
`$ npm install`

**Comment by asashay** [comment]
Thank you for comprehensive answer. It has helped to launch the app but it appears that NavigationExperimental has got massive changes and needs to be updated in the kit to navigate properly.
