### ISSUE TITLE
Use Jest?

### ISSUE THREAD

**Issue by cpojer** [futurice/pepperoni-app-kit#121]
Hey everyone!

This project looks like a great starter kit. Snowflake itself ships with Jest and we have worked with Barton and other RN engineers to make Jest really really good for react-native and we introduced the concept of snapshot testing. I just wanted to bring it up to you guys and I linked to two blog posts that explain how we changed Jest recently and what we did to improve:

facebook.github.io/jest/blog/2016/07/27/jest-14.html
facebook.github.io/jest/blog/2016/09/01/jest-15.html

I'm happy to help with any questions if you decide to make the switch. If not, that is fine too – just close this issue :)

**Comment by jhabdas** [comment]
Here's a recent article from @RyanCCollins which might help for those interested:
https://medium.com/@ryancollinsio/testing-react-redux-applications-fee79ac0087f

**Comment by krivachy** [comment]
Thanks, we'll look into this soon!

**Comment by justinwoo** [comment]
We fixed with with #135 👍
