### ISSUE TITLE
Pass my own props to a container?

### ISSUE THREAD

**Issue by wandonye** [futurice/pepperoni-app-kit#123]
If I want to pass my own props to a view which has a container, can I do 
```
export default connect(
  (state, myownprops) => ({
    navigationState: state.get('navigationState').toJS(),
    myownprop: myownprops.prop
  }),
...
```
Or is there another suggested approach?

Also it seems in the starter kit, context was never used, is there any reason behind it?
Thx~

**Comment by fabriziomoscon** [comment]
`connect` comes from `redux` and it is used to mount properties from a section of the store. In your example `navigationState` is the key where the navigation reducer is mounted. So `myownprop` must be the key for another reducer, for example a reducer of another module.

To pass your own props you simply pass them to the JSX element

```
import MyView form `myView/MyViewContainer`

...
render() {
   return (
      <MyView myProperty={false} />
   )
}
```

after that you will find `myProperty` in the view as `this.props.myProperty`

I hope this helps...
