### ISSUE TITLE
PR: Add support for `eslint-plugin-flowtype-errors`

### ISSUE THREAD

**Issue by amilajack** [futurice/pepperoni-app-kit#126]
This plugin allows flow to be run as an eslint plugin 🎉 Would a PR for this be welcome?

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

**Comment by krivachy** [comment]
@amilajack Thanks for your interest in Pepperoni! 🍕 🚀 
Right now Pepperoni isn't using Flow, so integrating this would require more flow modules/plugins to be added? Also we don't want to mandate users of Pepperoni to use Flow, so maybe a PR would be best in the newly created #129. What do you think?

**Comment by amilajack** [comment]
That would be great. Thanks!
