### ISSUE TITLE
Readme says "you can't rename a fork", but you can

### ISSUE THREAD

**Issue by rjmunro** [futurice/pepperoni-app-kit#127]
It then goes on to recommend instructions you may not need.

What you may not be able to do is take a fork private, which you might like to do if you are making the next big thing in apps.

(Here is an example of a fork that has been renamed: https://github.com/rjmunro/chrome-improved-font-changer)

**Comment by krivachy** [comment]
Thanks for spotting the error! Will be fixed in #128 🍕 🚀
