### ISSUE TITLE
React-Native No suitable URL request found

### ISSUE THREAD

**Issue by EQuimper** [futurice/pepperoni-app-kit#131]
I got this error when running `react-native run-ios`.

I don't know how to figure a way to handle this.

![](https://i.stack.imgur.com/6c0Ii.png)

**Comment by krivachy** [comment]
Hi @EQuimper, thanks for raising the issue. 🍕 🚀 
Can you please provide more information on the following things:
 * Is this a clean checkout of pepperoni-app-kit or have you modified the code already? (i.e. could the bug be on your side)
 * Have you followed all setup instructions here: https://github.com/futurice/pepperoni-app-kit/blob/master/docs/SETUP.md ?
 * Have you tried a cleaning build artifacts, `rm -rf node_modules`, and similar?

**Comment by EQuimper** [comment]
hey @krivachy thank you first for your boilerplate ;).

So what happen it's a got a client who send me the app. He want me to continue the work of an other dev. I did the install etc. Not first time I use your boilerplate ;) But when I got to finish the auth0 setup I got this .....

**Comment by EQuimper** [comment]
Gonna try the `rm-rf node_modules`

**Comment by EQuimper** [comment]
So I confirm after done `rm -rf node_modules/ && npm cache clean && npm install` I got the same problem

**Comment by chadrien** [comment]
I'm not sure if it's related to the setup. `No suitable URL request handler` is a `fetch` error. Somewhere in your codebase you probably have a `fetch('file://something')` and this `fetch` throws an error (maybe the file does not exist on your machine?).

**Comment by tino-junge** [comment]
Closing this now due inactivity.

**Comment by azizmobarak** [comment]
+1

**Comment by VanLong-official** [comment]
+1
