### ISSUE TITLE
NavigationView is not working in 0.35

### ISSUE THREAD

**Issue by anton-aleksandrov** [futurice/pepperoni-app-kit#136]
Hey
I've used this kit about 2-3 weeks ago, it was ok. 
Today i've cloned repo again, but this time the `NavigationExperimental` doesn't work properly.

Screenshot here:
[simulator screen shot 19 oct 2016 13 19 27](https://cloud.githubusercontent.com/assets/12139447/19515164/f83c69c6-95fe-11e6-82f3-db7c1d0f7390.png)

I've just started investigating, if someone has ideas - please let me know.

RN cli is up to date
no errors in debugging console
`NavigationView` `render` method initiated, but `renderHeader` is not. ([Link](https://github.com/futurice/pepperoni-app-kit/blob/26df0277911d8d54dbdbbcd3eb8766c8c5265d99/src/modules/navigation/NavigationView.js#L35))

...to be continued

**Comment by anton-aleksandrov** [comment]
https://github.com/facebook/react-native/releases/tag/v0.32.0

**Comment by krivachy** [comment]
Thanks @anton-aleksandrov, yes this is a regression that the RN 0.35 upgrade introduced, the positioning used to be absolute, now it isn't. If you have time a PR would be appreciated, if not we'll do our best to fix it as soon as possible.

**Comment by tino-junge** [comment]
@anton-aleksandrov @krivachy I've created a PR #145 which fixes the title issue
