### ISSUE TITLE
Header disappeared after RN 0.35 upgrade

### ISSUE THREAD

**Issue by chadrien** [futurice/pepperoni-app-kit#137]
Before upgrade (f172c21)

![screen shot 2016-10-20 at 11 22 06](https://cloud.githubusercontent.com/assets/1788218/19552340/1bdfaa14-96b8-11e6-9a90-b2eaeb0a61a2.png)

After upgrade (549fd09)
![screen shot 2016-10-20 at 11 24 45](https://cloud.githubusercontent.com/assets/1788218/19552341/1e439734-96b8-11e6-84c4-92d688ef8d57.png)

refs #130

**Comment by krivachy** [comment]
@chadrien is this a duplicate of #136?

**Comment by chadrien** [comment]
Oh right, missed this one, sorry
