### ISSUE TITLE
Navigation redirect best practices

### ISSUE THREAD

**Issue by anton-aleksandrov** [futurice/pepperoni-app-kit#139]
Hey
Guys, how do you handle redirect here? For example, if i need to redirect user to logIn scene?
I'm asking more about the approach generally rather than about detailed implementation.

Do you use `NavigationStateUtils.replaceAtIndex`, or tabs or making `AuthRouter.js` constantly check specific conditions and replace state on the fly or something else?

**Comment by fabriziomoscon** [comment]
In the login scenario, you would have 2 possibilities.

active tap:
Users would tap on login and so generate an ACTION which can either generate a change of STATE or you can push a VIEW_CONTAINER that you previously defined in `AppRouter.js`

indirect condition:
You want to show a login screen as a result of some ACTIONs, for example some API calls returned 401. In this case I would bind the render of the login MODAL to a special STATE key. for example `auth.shouldForceLogin` or something more sensible.

**Comment by krivachy** [comment]
@anton-aleksandrov Thanks for your interest in Pepperoni 🍕 🚀 Do you have any follow up questions? If not we'll be closing this issue.
