### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by gungungun93** [futurice/pepperoni-app-kit#143]
Hey Guys
I get an error when I'm trying to run this project by Xcode instead of using react-native run-ios command. Any idea?

**Comment by tino-junge** [comment]
Hey @gungungun93, thanks for your interest in Pepperoni 🍕 🚀 ! When building the project with XCode are you using the `.xcworkspace` file and not the `.xcodeproj` file? Let me know if this solves your issue.

**Comment by gungungun93** [comment]
thanks @tino-junge for responding my question. I open Xcode by double click . xcodeproj and run the app.

**Comment by tino-junge** [comment]
Try opening the `.xcworkspace` file instead. So either double click on it or run `open PepperoniAppTemplate.xcworkspace` in your terminal.

**Comment by gungungun93** [comment]
Wow that's magic. Thank @tino-junge for your time. :)

**Comment by tino-junge** [comment]
Great, you're welcome :) I've added a note to our iOS setup readme to make that more clear.
