### ISSUE TITLE
[ROADMAP] Navigation

### ISSUE THREAD

**Issue by fabriziomoscon** [futurice/pepperoni-app-kit#149]
I am looking forward to the new navigation library announced here:
https://github.com/facebook/react-native/wiki/Roadmap

> Right now there are a large number of navigation libraries. We don't think one navigation library will be enough for every use case, but we do think we can make it better. The goal is for this new navigation library to be ideal for apps that handle navigation in JavaScript. Once it is released and stable, we can deprecate Navigator, NavigationExperimental, and ExNavigation.

**Comment by fabriziomoscon** [comment]
related: https://dev.to/machadogj/react-navigation-with-redux-and-immutablejs?utm_content=buffer39860&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by sercanov** [comment]
NavigationExperimental is a torture right now. Looking forward to see it changed to ReactNavigation

**Comment by fabriziomoscon** [comment]
feel free to sketch something together if you have inspiration. I don't see myself having the time for the next few months.

**Comment by sercanov** [comment]
I think I'll have time next week. I will try to properly design it to React Navigation

**Comment by FruitieX** [comment]
Would be very nice to have an experimental branch on Pepperoni that uses `react-navigation`. I'll also see if I can find some time for integrating it.

**Comment by FruitieX** [comment]
[It's happening](https://github.com/futurice/pepperoni-app-kit/tree/feature/react-navigation) :tada: :tada: :rocket:

**Comment by FruitieX** [comment]
https://github.com/futurice/pepperoni-app-kit/pull/188

**Comment by tino-junge** [comment]
We finally changed to react-navigation with merging #189 :) thanks for submitting the PR @FruitieX !
