### ISSUE TITLE
DeveloperMenu for Android

### ISSUE THREAD

**Issue by tino-junge** [futurice/pepperoni-app-kit#15]
Only for iOS right now, because we are using `ActionSheetIOS` currently to display DeveloperMenu. Possible solution might be https://www.npmjs.com/package/react-native-action-sheet

**Comment by fabriziomoscon** [comment]
I got this working. I will submit a PR as soon as my other gets merged since I am basing my changes on the new react-native

**Comment by jevakallio** [comment]
@fabriziomoscon I implemented a super simple solution for this on Android already, so no need to submit a PR 👍
