### ISSUE TITLE
Unrecognized font family 'FontAwesome'

### ISSUE THREAD

**Issue by krzysztofp** [futurice/pepperoni-app-kit#163]
I've build the application today using XCode and got the following error - it's a fresh clone:
![image](https://cloud.githubusercontent.com/assets/1634660/21506508/e2ccf99a-cc70-11e6-8ae2-7a7506225cc4.png)

MacOS Sierra: 10.12.2
XCode: 8.2.1 (8C1002)
npm: 3.10.9
node: v7.2.1
react-native-cli: 2.0.1
react-native: 0.37.0

I needed to run $react-native upgrade, due to the previous issue found here on the Issues list.

How can I solve this?

**Comment by krzysztofp** [comment]
Actually [this command](https://github.com/oblador/react-native-vector-icons/issues/135#issuecomment-263470798) helped me after $react-native upgrade:

    react-native link react-native-vector-icons

**Comment by krivachy** [comment]
Closing this as the issue seems to be resolved.
