### ISSUE TITLE
Problem running react-native run-ios

### ISSUE THREAD

**Issue by osolano** [futurice/pepperoni-app-kit#178]
Hello,

I've just tried a fresh clone of the project and followed the getting started instructions but am getting blocked by this error

```Can't find variable Symbol```

Tapping the first cell on this screenshot points to this area

```var isEffectSymbol = Symbol('isEffect');```

![image](https://cloud.githubusercontent.com/assets/280426/22836031/c2f09ace-ef6f-11e6-8318-b10af52f6710.png)

I performed the steps exactly as mentioned on Readme

**Comment by tino-junge** [comment]
Hi @osolano thanks for reporting this issue. I've just build a fresh clone of pepperoni without issues. I've used the following steps: 
```
git clone git@github.com:futurice/pepperoni-app-kit.git
cd pepperoni-app-kit
yarn install
react-native run-ios
```
Could you specify your environment setup?

**Comment by osolano** [comment]
Sure, I'm on 
react-native-cli: 2.0.1
react-native: 0.40.0
yarn v0.19.1

**Comment by osolano** [comment]
I also just tried update react-native-cli and still have the same error.

```
react-native-cli: 2.0.1
react-native: 0.41.2
```

**Comment by tino-junge** [comment]
Your problem might be related to ES2016 `Symbols` (see here for more: https://github.com/facebook/react-native/issues/4676). Someone was able to fix it for iOS to install a babel polyfill (https://babeljs.io/docs/usage/polyfill/). Let me know if it solves your issue.

**Comment by tino-junge** [comment]
Closing this now due to inactivity. Can reopen if the issue still occurs.

**Comment by Charlie-Hua** [comment]
Adding this line to the top of `index.ios.js` fixes it for me:
```javascript
import 'es6-symbol/implement';
```

**Comment by FruitieX** [comment]
IIRC iOS < 9.0 does not implement Symbol in their JSC engine. Since #192 was merged, we are using a patched version of `redux-loop` which uses a Symbol polyfill when needed, which means the problems arising from missing Symbol will be fixed on all platforms regardless of version.
