### ISSUE TITLE
Animated transition between tabs

### ISSUE THREAD

**Issue by anton-aleksandrov** [futurice/pepperoni-app-kit#196]
Is there conventional way to simulate `NavigationExperimental` transition when switching between tabs? Or may be it's possible to use `NavigationExperimental` itself to do those transitions?

**Comment by sercanov** [comment]
If you mean the transition animation, yes you can. But you have to rebuild navigation state without `tabs` object, then NavigationExperimental's `jumpToIndex` will animate it like pushing. 

I've been trying to get rid of that animation but it doesn't seems possible right now ^^
