### ISSUE TITLE
Upgrade to React Navigation 1.0.0-beta.10 to remove `View.propTypes` warning

### ISSUE THREAD

**Issue by nlhkh** [futurice/pepperoni-app-kit#204]

**Comment by fabriziomoscon** [comment]
I have also experienced some differences between master and "react-navigation": "^1.0.0-beta.11".

I think the best for Pepperoni would be to wait a stable release of react-navigation, because until then the API will keep on changing.

**Comment by FruitieX** [comment]
Working on it. Here's a branch with all dependencies updated: https://github.com/futurice/pepperoni-app-kit/tree/maintenance/upgrade-dependencies

**Comment by danieljharvey** [comment]
Hi - we are now using React Navigation 1.0.0-beta 11 as it was the best fit compatibility-wise for React Native 0.49.3 -  see #223 - this should resolve propTypes warning.
