### ISSUE TITLE
Not working with react native version 0.47.1

### ISSUE THREAD

**Issue by tatvamac** [futurice/pepperoni-app-kit#215]
Is there any solution to work with start kit on the latest version of react-native?
Any help will be appreciated.

**Comment by FruitieX** [comment]
I believe integrating with create-react-native-app would be our best bet for this project, that way we don't need to care (as much) about React Native versions anymore.

**Comment by danieljharvey** [comment]
Hi @FruitieX - agree wholeheartedly re: tracking CRNA and working as an add-on to it as a good aim for project (and your branch/screens are looking great) - however in the meantime have updated project to React Native version 0.49.3 (#223) mostly because I like having a terrible time.
