### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): `tabBar` cannot be defined as a function in navigation options for `Counter` screen

### ISSUE THREAD

**Issue by badis** [futurice/pepperoni-app-kit#216]
I have started a new app following the installation instructions:

```
git clone https://github.com/futurice/pepperoni-app-kit.git
cd pepperoni-app-kit
yarn install
react-native run-android
```
At first run i got this error: 

```
Possible Unhandled Promise Rejection (id: 0): `tabBar` cannot be defined as a function in navigation options for `Counter` screen
```

![screenshot from 2017-08-17 11-10-56](https://user-images.githubusercontent.com/3008693/29407647-f859625c-833c-11e7-9f40-c6a0001c9a05.png)

Note: All tests run successfully !

![screenshot from 2017-08-17 11-14-00](https://user-images.githubusercontent.com/3008693/29407714-35fa0468-833d-11e7-90de-28fdc58d1852.png)

Thanks

**Comment by kagmanoj25** [comment]
just run below command then restart your VSC then run the android command you will get output
"**yarn add react-navigation**"

**Comment by badis** [comment]
@kagmanoj25  react-navigation is already installed.
I have tried to install it another time and it works! may be it's cache issue in npm modules or something liket that!
