### ISSUE TITLE
Is there an easy way to change the App name?

### ISSUE THREAD

**Issue by VashMar** [futurice/pepperoni-app-kit#23]
Currently it's all under Kindling, if we want to build on top of the kit, are there commands we can run to personalize it to our own project?

**Comment by VashMar** [comment]
We just brute forced it the renaming.

**Comment by VashMar** [comment]
Ended up just renaming manually, would be nice if there was an easier way though.

**Comment by jevakallio** [comment]
Oh yes, documenting this is on our todo-list! The app is currently called "Kindling" (the original codename  for the project), we will need to rename it anyway.

The way to go about this will probably be something like running the following in the root directory of your project:

```
sed -i 's/Kindling/YourAppName/g' *
```

(Above not tested)

**Comment by chadrien** [comment]
@jevakallio will it work in the cases of `com.kindling` in android build configuration?

Tested and (for now working):

* change the `name` in `package.json`
* run `react-native upgrade`
  * on file conflict, press `d` to get the diff and locate the name changes (it will be from `Kindling` to `YourAppName` or from `kindling` to `yourappname` mostly)
  * once you located the name changes, apply them manually and say no to the upgrader so you don't lose additional stuff brought by Pepperoni
* run `rm -rf Kindling Kindling.xcodeproj Kindling.xcworkspace KindlingTests` (new xcode files should have been generated for your new app name)
* edit `YourAppName.xcodeproj/project.pbxproj` and look for `OTHER_LDFLAGS`. Change its value to `$(inherited)` (in my case it was from `-ObjC` or something)
* run `(cd ios; pod install)`
* change `Kindling` to `YourAppName` in `index.ios.js` and `index.android.js`

And you should be good to go.

**Comment by jevakallio** [comment]
@chadrien thanks for the instructions! I'll have to read those through and test for iOS and Android. Ideally we will need a solution that doesn't require running `reacf native upgrade`, as we will soon have a need for customisation in project files.

I think a shell script or a small cli tool bundled with the Pepperoni repo might be a way to go. This is something we will probably need eventually anyway for helping users bring in latest changes from the template to their projects.

**Comment by jevakallio** [comment]
Furthermore we should rename the Kindling directory to something app-independent, so it doesn't need to be renamed by developers.

**Comment by chadrien** [comment]
@jevakallio I will try to write such a shell script and open a PR if it goes well.

**Comment by jevakallio** [comment]
@chadrien sweet!

**Comment by chadrien** [comment]
@jevakallio OK I think I'am on something working (`run-ios` and `run-android` both start the app and it seems to be functional).

Before opening a PR, could you tell me in which dir you'd like the script file to be, and what would be its name?

**Comment by jevakallio** [comment]
@chadrien I think the file could be something like /support/rename.sh, or .js depending on what you wrote it in. 

As a part of the PR, could you also do a rename from Kindling to PepperoniAppTemplate, and the same for the lowercase Android strings? That would be clearer and more guaranteed to be unique.
