### ISSUE TITLE
Follow the official steps but an error occurred

### ISSUE THREAD

**Issue by Lanceloft** [futurice/pepperoni-app-kit#231]
terminal show:
ERROR  ENOENT: no such file or directory, lstat '/Users/pk888888/pk/demo/pepperoni-app-kit/ios/build/ModuleCache/26K6A22R0VJ3L/CoreImage-2L8M44C0CYIPM.pcm-20f85f0b'

and the app show:
No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0

just follow the step:
git clone https://github.com/futurice/pepperoni-app-kit.git
cd pepperoni-app-kit
yarn install
react-native run-ios

**Comment by youzi** [comment]
I had the same issue. An additional `npm install` solved it for me. https://github.com/facebook/react-native/issues/12754#issue-212323726.

**Comment by tino-junge** [comment]
closing this now due to inactivity. In case the issue still persists we can re-open it
