### ISSUE TITLE
Error while building the ios app

### ISSUE THREAD

**Issue by maephisto** [futurice/pepperoni-app-kit#25]
I can build some other react native projects, but when i am building pepperoni i am getting following error:

`=== BUILD TARGET RCTVibration OF PROJECT RCTVibration WITH CONFIGURATION Debug ===

Check dependencies

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/mm/Personal/projects/pepperoni-app-kit/ios/build/Build/Intermediates/A0RNLock.build/Debug-iphonesimulator/A0RNLock.build/Objects-normal/x86_64/A0LockReact.o A0RNLock/Core/A0LockReact.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/Kindling.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/mm/Personal/projects/pepperoni-app-kit/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Kindling.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:441:13)
    at Object.execFileSync (child_process.js:461:13)
    at _runIOS (runIOS.js:91:34)
    at runIOS.js:24:5
    at tryCallTwo (/Users/mm/Personal/projects/pepperoni-app-kit/node_modules/react-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/mm/Personal/projects/pepperoni-app-kit/node_modules/react-native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/mm/Personal/projects/pepperoni-app-kit/node_modules/react-native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/mm/Personal/projects/pepperoni-app-kit/node_modules/react-native/local-cli/cli.js:87:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)`

**Comment by jevakallio** [comment]
Hmm.. have you edited the project bundle identifier in project settings in XCode? `CFBundleIdentifier` in Info.plist is defined as follows:
```
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
```

Is it possible that that value is somehow incorrectly set?

**Comment by maephisto** [comment]
No, did not edit anything - did just the following:
1. git pull origin master
2. npm install
3. cd pepperoni-app-kit
4. react-native run-ios

**Comment by jevakallio** [comment]
I think there's a couple of more steps to do, such as installing the Cocoapods dependencies. Try following the [setup guide](https://github.com/futurice/pepperoni-app-kit/blob/master/docs/SETUP.md) and let us know if it still doesn't work.

**Comment by maephisto** [comment]
Thanks, I hadn't noticed the setup guide. 
I've followed the guide and right now i encountered a new problem, during `pod install`:
`[!] The dependency `Lock (~> 1.24)` is not used in any concrete target.
The dependency `Lock/TouchID` is not used in any concrete target.
The dependency `Lock/SMS` is not used in any concrete target.
The dependency `Lock/Email` is not used in any concrete target.`

**Comment by 3bola** [comment]
Could this be related to auth0/react-native-lock 0.2.0 release? I got everything working after installing the default version and patching it with this: futurice/react-native-lock/commit/7c356c8602ebc2cd1f99dee692c3a6a8d7c7aa03

**Comment by tylerl0706** [comment]
That merge fixed this issue for me. However, now I get this:

![](https://i.imgur.com/G380LFO.pnghttps://i.imgur.com/G380LFO.png)

I wish that I had more information for you. I confirmed that my `AUTH0_CLIENT_ID`
and `AUTH0_NAMESPACE` are correct. However, the namespace for mine is <name>.auth0.com instead of the <name>.eu.auth0.com one used in the `Setting up the Starter Kit` guide. Let me know how I can help.

**Comment by maephisto** [comment]
The update + auth0 credentials worked awesome.
All works now! Thank you!

**Comment by tylerl0706** [comment]
I cloned the repo again starting fresh and the following error occurs when I run `react-native run-ios`:

![](https://i.imgur.com/k9iBjAv.png)

The index.ios.js file is in the root of the directory though... any ideas?

**Comment by jevakallio** [comment]
One thing that sometimes helps when the RN packager gets confused is to restart the shell process that runs the packager (often a separate terminal window) and run-ios again.

**Comment by tylerl0706** [comment]
@jevakallio spot on! I totally forgot about that window hidden behind everything else. I closed it and reran run-ios and it worked!

**Comment by jevakallio** [comment]
No reported issues open in this thread anymore, closing. If you have any more (different) problems, please open new issues for them.

**Comment by chrisciampoli** [comment]
I have the same error after following all of the steps in the setup guide

**Comment by chrisciampoli** [comment]
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/chris/projects/haplo/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/PepperoniAppTemplate.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:441:13)
    at Object.execFileSync (child_process.js:461:13)
    at _runIOS (/Users/chris/projects/haplo/node_modules/react-native/local-cli/runIOS/runIOS.js:91:28)
    at /Users/chris/projects/haplo/node_modules/react-native/local-cli/runIOS/runIOS.js:24:1
    at tryCallTwo (/Users/chris/projects/haplo/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/chris/projects/haplo/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/chris/projects/haplo/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/chris/projects/haplo/node_modules/react-native/local-cli/runIOS/runIOS.js:23:8)
    at Object.run (/Users/chris/projects/haplo/node_modules/react-native/local-cli/cliEntry.js:95:11)
    at Object.<anonymous> (/Users/chris/.nvm/versions/node/v5.0.0/lib/node_modules/react-native-cli/index.js:88:7)

**Comment by abuammar** [comment]
can some help me, i get this error

The following build commands failed:
	CompileC /Users/ws1/Code/mobile/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapPolyline.o AirMaps/AIRMapPolyline.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ws1/Code/mobile/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapUrlTileManager.o AirMaps/AIRMapUrlTileManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
Installing build/Build/Products/Debug-iphonesimulator/WS1.com.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/WS1.com.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
