### ISSUE TITLE
Pod install fails

### ISSUE THREAD

**Issue by kishanj918** [futurice/pepperoni-app-kit#31]
When i ran pod install, i got  **[!] Unable to find a specification for `TouchIDAuth (~> 0.1)` depended upon by `Lock/TouchID`.**

**Comment by bartonhammond** [comment]
+1

```pod --version``` -> 1.0.0

I get:
```
~/projects/HappyHour/pepperoni-app-kit/ios (master)$ pod install
Re-creating CocoaPods due to major version update.
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Lock (~> 1.24)` required by `Podfile`
- `Lock (= 1.26.0)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `Lock (~> 1.24), Lock (= 1.26.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by jevakallio** [comment]
Thanks for reporting and confirming this. We'll look into this - most likely the case is that our developers are still on CocoaPods 0.x and the latest changes have not been tested with 1.0

**Comment by bartonhammond** [comment]
Thanks @jevakallio.  It's a show stopper.

**Comment by jevakallio** [comment]
Yup - I'm aware. If you know what the appropriate fix is, feel free to submit a patch. I'm in GMT & on mobile, earliest this will be fixed by me is tomorrow.

**Comment by bartonhammond** [comment]
I made PR:[#34](https://github.com/futurice/pepperoni-app-kit/pull/34) to document that ```pod repo update``` is required now if your ```pod --version``` is 1.0.0.   It seems to me that ```pod``` updated it's own version as 1.0.0 was just released 20 days ago [https://github.com/CocoaPods/CocoaPods-app/releases/tag/1.0.0](https://github.com/CocoaPods/CocoaPods-app/releases/tag/1.0.0) and I didn't update it manually.

@kishanj918 - could you validate if running ```pod repo update``` in your ```ios``` directory fixes this?

**Comment by kishanj918** [comment]
@bartonhammond `pod repo update` didn't work!

**Comment by bartonhammond** [comment]
!well rats, my bad.. I should have made a new issue.

**Comment by jevakallio** [comment]
I upgraded CocoaPods to 1.0, and `pod install` worked without `pod repo update`.

I previously had CocoaPods installed from Homebrew, but because the latest version on brew was still 0.39, I had to install CocoaPods 1.0 from `gem`. This might have led to the different result.

In any case, I can't replicate the issue easily. If `pod repo update` doesn't work, how about deleting `Podfile.lock` and installing from afresh?

In addition, make sure your Pepperoni repo contains commit https://github.com/futurice/pepperoni-app-kit/commit/db6ee374ce3985be3befd5e09ec4b2143a811c73, which updated the podfile format.

**Comment by bartonhammond** [comment]
I just don't know enough about CocoaPods to be much of help.  

I wonder if it would be better to separate my comment above out to a separate issue that users can search for.  If they get any of those messages from ```pod install``` they would know ```pod repo update``` fixes it.  Of course, the patch could have better clarification of the condition.  Seems it's a one time setup issue.

**Comment by dunphyben** [comment]
I also ran into the following issue

```
$ pod install
Re-creating CocoaPods due to major version update.
Analyzing dependencies
[!] Unable to find a specification for `Lock (~> 1.24)`
$ pod --version
1.0.0
```

But `pod repo update` is failing. Are there too many people requesting this concurrently? It seems to be dragging. My internet speed is currently 84 Mbps

```
ben$ pod repo update
Updating spec repo `master`
Performing a deep fetch of the `master` specs repo to improve future performance
[!] /usr/bin/git fetch --unshallow

error: RPC failed; curl 56 SSLRead() return error -36
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

**Comment by jevakallio** [comment]
@dunphyben fetches from CocoaPods fail mysteriously sometimes. They use GitHub as their backend, and repository clones are rate limited.

Please try again? I would recommend you pull the latest changes from Pepperoni master - we have updated CocoaPods to 1.0 and React Native 0.26, and the sooner you get those changes in, the easier they will be to merge.

**Comment by emmby** [comment]
I just did a fresh install and everything worked fine with just a `pod install`.

**Comment by tdurand** [comment]
I have the same issue, cloned repo, npm install and then:

> [!] Unable to find a specification for Lock (~> 1.24)

![screen shot 2016-08-19 at 17 42 21](https://cloud.githubusercontent.com/assets/533590/17826239/50ed9db0-6634-11e6-9039-7c49d00dee69.png)

Could i be something related to server problem with CocoaPods ? (i'm new to iOS i don't know anything about pod ;) ) 

As you can see in screenshot i have pod version 1.0.1

**Comment by tdurand** [comment]
Doing a 

```
pod repo remove master
pod setup
```
solved the problem !

**Comment by huperezs** [comment]
Thanks
