### ISSUE TITLE
env.js Setup clarification

### ISSUE THREAD

**Issue by bartonhammond** [futurice/pepperoni-app-kit#33]
The Setup Guide has:

```
AUTH0_CLIENT_ID: '<CLIENT_ID>',
AUTH0_NAMESPACE: '<APP_NAME>.eu.auth0.com'
```
In Auth0 Application Settings, there is no "NameSpace" but there is "Domain" as shown below. Does ```NAMESPACE``` === ```DOMAIN```?  If so, maybe updating docs and code would be worthwhile.  If not, some clarification should be provided to explain what/where this ```NAMESPACE``` value is.

<img width="887" alt="screen shot 2016-05-31 at 4 31 01 pm" src="https://cloud.githubusercontent.com/assets/1282364/15691231/270ef1ae-274d-11e6-9938-1982a5be4e0c.png">

**Comment by jevakallio** [comment]
@bartonhammond thanks for reporting. Does this fix the issue https://github.com/futurice/pepperoni-app-kit/pull/35/files

**Comment by bartonhammond** [comment]
I think that is more clear.
