### ISSUE TITLE
The app feels slow for iPhone 5S (debug mode)

### ISSUE THREAD

**Issue by dropfen** [futurice/pepperoni-app-kit#39]
Hey Guys,
my first experiments with RN was a very simple Tabs Apps without stores and so on.
Then I discovered pepperoni with all the good practices and the proper architecture.

But my first impression on a device is, that the app feels very slow on an iPhone 5S!

Has somebody else the same feeling?

**Comment by krivachy** [comment]
@dropfen Are you running it in Release mode or Debug mode on the phone? Release mode has logging disabled and given that we're logging all actions and state exchanges it can become quite expensive.

**Comment by dropfen** [comment]
@krivachy Oh yeah, you are right, this will be the issue, it needs to communicate to the debugger, log it and then back again. yep that makes sense.

**Comment by dropfen** [comment]
@krivachy thx for clarifying 👍

**Comment by krivachy** [comment]
Still, give it a try! We've mostly been testing on iPhone 6/6S, so it's totally possible that the 5S will feel slow. I'll leave this issue open for a bit 🍕

**Comment by jevakallio** [comment]
Thanks for reporting this, @dropfen. Our documentation is still work-in-progress, I'll document the performance implications of different builds as part of https://github.com/futurice/pepperoni-app-kit/issues/41.

**Comment by dropfen** [comment]
@jevakallio #41 would be great, I guess there are more steps to be done, than just switching the Release Bits. Anyway, I'll follow the docs, and thanks for investing time in pepperoni, it makes it easy to learn the eco-system ;)
