### ISSUE TITLE
Feature request: icons on the tabbar

### ISSUE THREAD

**Issue by krivachy** [futurice/pepperoni-app-kit#40]
A common design is to have Icons on the tab-bar, so having it built in would be nice.

**Comment by Lapanti** [comment]
I can PR my usage of the icons tomorrow (uses some library that I can't remember at the moment)

**Comment by jhabdas** [comment]
Here's an [example of tab bar scene navigator](https://github.com/jhabdas/SmartphoneSymphony/blob/master/src/components/TabBarNavigator.js) which could be referenced in a port if it helps. iOS only.

**Comment by tino-junge** [comment]
Thanks to @Lapanti we added now icons for tabs in Pepperoni 🚀  !
