### ISSUE TITLE
Can't run this on 0.26 - naming collision 

### ISSUE THREAD

**Issue by sudharsan1988** [futurice/pepperoni-app-kit#47]
Hi, 

I have tried it on 0.26 today and I couldn't make the "npm start" and it throws me an error as below,

Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: ReactDOMOption
  Paths: /home/sid/react/pepperoni-app-kit/node_modules/react/lib/ReactDOMOption.js collides with /home/sid/react/pepperoni-app-kit/node_modules/react-native-mock/node_modules/react/lib/ReactDOMOption.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: ReactDOMOption
  Paths: /home/sid/react/pepperoni-app-kit/node_modules/react/lib/ReactDOMOption.js collides with /home/sid/react/pepperoni-app-kit/node_modules/react-native-mock/node_modules/react/lib/ReactDOMOption.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/home/sid/react/pepperoni-app-kit/node_modules/react-native/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:160:15)
    at /home/sid/react/pepperoni-app-kit/node_modules/react-native/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:125:25

**Comment by fabriziomoscon** [comment]
running `npm start` I had something similar today, after upgrading my project (which is base on pepperoni-app-kit) to `react-native 0.27.2`:

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: ReactPerf
  Paths: <PROJECT_ROOT>/node_modules/react/lib/ReactPerf.js collides with <PROJECT_ROOT>/node_modules/react-native-mock/node_modules/react/lib/ReactPerf.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: ReactPerf
  Paths: <PROJECT_ROOT>/node_modules/react/lib/ReactPerf.js collides with <PROJECT_ROOT>/node_modules/react-native-mock/node_modules/react/lib/ReactPerf.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (<PROJECT_ROOT>/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:162:15)
    at <PROJECT_ROOT>/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:127:25
```

I fixed it doing:

```
rm -fr node_modules
npm install
npm start #again
```

Hopefully this will fix your issue as well

**Comment by sudharsan1988** [comment]
I tried but no luck, it' still keep on getting stopped due to naming collision issue with react/lib, react-native-mock/node_modules/react/lib. 

Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react
  Paths: /home/sid/react/pepperoni-app-kit/node_modules/react/package.json collides with /home/sid/react/pepperoni-app-kit/node_modules/react-native-mock/node_modules/react/package.json

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: react
  Paths: /home/sid/react/pepperoni-app-kit/node_modules/react/package.json collides with /home/sid/react/pepperoni-app-kit/node_modules/react-native-mock/node_modules/react/package.json

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/home/sid/react/pepperoni-app-kit/node_modules/react-native/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:160:15)
    at /home/sid/react/pepperoni-app-kit/node_modules/react-native/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:138:25

**Comment by fabriziomoscon** [comment]
could you paste `dependencies` from your `package.json`?

**Comment by sudharsan1988** [comment]
@fabriziomoscon, I am copying my package.json content here,

{
  "name": "PepperoniAppTemplate",
  "author": "Futurice",
  "description": "React Native App Starter Kit for Android and iOS",
  "license": "MIT",
  "homepage": "http://getpepperoni.com",
  "bugs": "https://github.com/futurice/pepperoni-app-kit/issues",
  "repository": {
    "type": "git",
    "url": "https://github.com/futurice/pepperoni-app-kit"
  },
  "keywords": [
    "React Native",
    "Starter Kit",
    "Bitrise",
    "Redux",
    "Auth0"
  ],
  "version": "1.0.0",
  "private": false,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "bundle:ios": "node ./node_modules/react-native/local-cli/cli.js bundle --platform ios --entry-file index.ios.js --bundle-output ios/PepperoniAppTemplate/main.jsbundle --dev=false --minify --verbose",
    "test": "mocha src/**/*.spec.js",
    "test:watch": "chokidar 'src/**/*.js' 'test/**/*.js' -c 'npm test'",
    "coverage": "rimraf coverage && istanbul cover --i=src/**/*.js _mocha -- src/**/*.spec.js",
    "check-coverage": "istanbul check-coverage"
  },
  "dependencies": {
    "bluebird": "^3.3.5",
    "es6-symbol": "^3.0.2",
    "immutable": "^3.7.6",
    "lodash": "^4.11.0",
    "moment": "^2.12.0",
    "react": "15.0.2",
    "react-dom": "15.0.2",
    "react-native": "^0.26.2",
    "react-native-gifted-spinner": "0.0.4",
    "react-native-lock": "futurice/react-native-lock#feature/customizedTheme",
    "react-redux": "^4.4.5",
    "redux": "^3.4.0",
    "redux-logger": "^2.6.1",
    "redux-loop": "^2.1.0",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.0.1"
  },
  "devDependencies": {
    "babel-cli": "^6.9.0",
    "babel-core": "^6.9.0",
    "babel-eslint": "^6.0.2",
    "babel-polyfill": "^6.9.0",
    "babel-preset-react-native": "^1.7.0",
    "babel-preset-stage-0": "^6.5.0",
    "chai": "^3.5.0",
    "chokidar-cli": "^1.2.0",
    "enzyme": "^2.2.0",
    "eslint": "^2.8.0",
    "eslint-plugin-babel": "^3.2.0",
    "eslint-plugin-react": "^4.3.0",
    "istanbul": "1.0.0-alpha.2",
    "mocha": "^2.4.5",
    "react-addons-test-utils": "15.0.2",
    "react-native-mock": "^0.2.2",
    "rimraf": "^2.5.2",
    "sinon": "^1.17.4"
  }
}

**Comment by fabriziomoscon** [comment]
what is your npm version?

**Comment by sudharsan1988** [comment]
It's 2.15.1

**Comment by fabriziomoscon** [comment]
Well, I bet that is the problem then. You should really consider upgrading to npm 3, that is a superior version which fixed many problems with v2.

**Comment by jevakallio** [comment]
Yes, I have managed to replicate this by using npm2 - the problem is that the `react-native-mock` component needs to define same module names as `react-native` itself, and this causes duplicate module entries.

I will document this in the setup guide.
