### ISSUE TITLE
Use standard.js for code formatting

### ISSUE THREAD

**Issue by emmby** [futurice/pepperoni-app-kit#50]
By using a standard set of JS formatting conventions, forks and mirrors of pepperoni will be less likely to run into merge conflicts every time they pull from the pepperoni upstream.

http://standardjs.com/

**Comment by justinwoo** [comment]
I'm often declaring vars and then destructuring in blocks below, so apparently I can't use standard.

e.g.

```js
let a, b;

if (cond1) {
  const c = (something)
  [a, b] = (whatever) // borked
}
```

**Comment by jevakallio** [comment]
@emmby thanks for the suggestion. StandardJS looks mostly okay, but it has some opinions we simply can't agree with, e.g. no semicolons. 

Its relentless no-customisation philosophy doesn't really suit us either - many users of Pepperoni will want to adapt the code style to their organisation's shared conventions, and we want to enable that.

That said, we could have a review of our `.eslintrc` and see if we could replace much of it with a default preset - this one is something I've written and upgraded from the pre-preset era :)

**Comment by emmby** [comment]
The nice thing about using an existing standard instead of inventing your own is that it's easy for everyone to use.  Standardjs has an ecosystem of tools built around it such as https://github.com/maxogden/standard-format.  With standard and standard-format, it's easy for anyone to 1) verify their code style is consistent (and build that check into tests), and 2) reformat it if necessary.

In addition, since pepperoni is a starter kit rather than a library, it's expected that users will be writing their own code in coexistence with pepperoni's code.  You're unlikely to get everyone who uses pepperoni to use your particular styling rules, which means that very pepperoni-based codebase is going to have a mix of pepperoni styles and other styles.  This means that everyone who wants to use pepperoni will run into issues when they pull new functionality from pepperoni.

While you obviously can't solve this for everyone who uses pepperoni, you can use an existing, popular standard so that anyone who uses that standard will have a smooth ride.  Using custom style rules guarantees that no one will have a smooth ride :)

If there's a different standard you want, that's fine too.  I just encourage you to pick the one that's most popular and meets your needs so that the widest swath of your community will be able to pull in all the great updates in pepperoni.
