### ISSUE TITLE
[DISCUSSION] upgrade Navigation [waiting for stability on NavigationExperimental]

### ISSUE THREAD

**Issue by fabriziomoscon** [futurice/pepperoni-app-kit#51]
UPDATE:
the repo mentioned below is no longer a good example considering all the breaking changes the folks at Facebook are making on the NavigationExperimental.
It is better to wait after `0.29` becomes stable to make any change on the navigation.

`NavigationExperimental` has changes in `0.30`
https://github.com/facebook/react-native/releases/tag/v0.30.0-rc.0

I think the current navigation could be improved and made it compatible with those changes. I was checking out this repo (whcih uses `react-native`#master https://github.com/jlyman/RN-NavigationExperimental-Redux-Example/blob/master/package.json#L12):

and notice few nice things in my opinion:
- more actions (https://github.com/jlyman/RN-NavigationExperimental-Redux-Example/blob/master/app/actions.js)
- a clean way to prevent the same route to be pushed (https://github.com/jlyman/RN-NavigationExperimental-Redux-Example/blob/master/app/reducers.js#L15)
- also a clean way to define initialNavigationState (https://github.com/jlyman/RN-NavigationExperimental-Redux-Example/blob/master/app/reducers.js#L5-L10)
- uses `NavigationTransitioner` which will be preferred to `NavigationAnimatedView` in the future (https://github.com/jlyman/RN-NavigationExperimental-Redux-Example/blob/master/app/containers/AppContainer.js#L28-L40)
(https://github.com/facebook/react-native/commit/7db7f78dc7d2b85843707f75565bcfcb538e8e51)

what's your opinion on this @jevakallio 

A good background giving context could be found here:
- https://github.com/ericvicenti/navigation-rfc/blob/master/Docs/NavigationOverview.md
- https://github.com/ericvicenti/navigation-rfc

**Comment by jevakallio** [comment]
Hi @fabriziomoscon, thanks for the thoughtful issue! I've just upgraded Pepperoni to React Native 0.28, where I did the [minimal changes](https://github.com/futurice/pepperoni-app-kit/commit/0f7de188801b619be8d811ec6c00eb3bfecac9ec) to fix the breaking API changes.

I definitely want to improve the navigation pattern, and those examples seems really interesting. I think a good time to do this would be when upgrading to RN 0.29, which introduces a new set of changes.

I will give it thought during the weekend and get back to this.

**Comment by jevakallio** [comment]
Okay @fabriziomoscon, I've now done the basic upgrades to React Native 0.29 at https://github.com/futurice/pepperoni-app-kit/pull/76, ready to start considering a bigger navigation refactor 🎉

**Comment by fabriziomoscon** [comment]
A nice tutorial has been updated by the guys at Facebook:
http://facebook.github.io/react-native/releases/next/docs/navigation.html#navigationexperimental

**Comment by fabriziomoscon** [comment]
AnimatedView is going to get removed in `0.30`
https://github.com/facebook/react-native/releases/tag/v0.30.0-rc.0
commit/explanation: 
https://github.com/facebook/react-native/commit/8ce7ad48b05a836e2a5f9fbdfa40c5874da47499

The NavigationTabView will need to use `NavigationTransitioner `
https://github.com/futurice/pepperoni-app-kit/blob/master/src/modules/navigation/NavigationTabView.js#L43

**Comment by fabriziomoscon** [comment]
@jevakallio I had a big fight over this over the past 2 days!
I think I am ready to show some work, submit a PR. I have taken all the new changes in `react-native` into consideration.

If you don't have objections or have already some work for this I can PR
