### ISSUE TITLE
Build failed on ios

### ISSUE THREAD

**Issue by WheelyWonka** [futurice/pepperoni-app-kit#54]
Hi Pepperoni team, 

I might look dumb but i can't get the starter kit to build on an iPhone. Everything works great into the simulator, but here's logs when I try to build it on a real device : 

```
ld: warning: directory not found for option '-L/Users/wt/Library/Developer/Xcode/DerivedData/test-gifqqwfpbaeomfhauvvrnvrqarmi/Build/Products/Debug-iphoneos/AFNetworking'
ld: warning: directory not found for option '-L/Users/wt/Library/Developer/Xcode/DerivedData/test-gifqqwfpbaeomfhauvvrnvrqarmi/Build/Products/Debug-iphoneos/CocoaLumberjack'
ld: warning: directory not found for option '-L/Users/wt/Library/Developer/Xcode/DerivedData/test-gifqqwfpbaeomfhauvvrnvrqarmi/Build/Products/Debug-iphoneos/Lock'
ld: warning: directory not found for option '-L/Users/wt/Library/Developer/Xcode/DerivedData/test-gifqqwfpbaeomfhauvvrnvrqarmi/Build/Products/Debug-iphoneos/Masonry'
ld: warning: directory not found for option '-L/Users/wt/Library/Developer/Xcode/DerivedData/test-gifqqwfpbaeomfhauvvrnvrqarmi/Build/Products/Debug-iphoneos/SimpleKeychain'
ld: warning: directory not found for option '-L/Users/wt/Library/Developer/Xcode/DerivedData/test-gifqqwfpbaeomfhauvvrnvrqarmi/Build/Products/Debug-iphoneos/TouchIDAuth'
ld: library not found for -lAFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

What am I missing ? I tried to re-run pod install, re-init project, nothing... Any ideas ?

Thanks for your help and your work on this kit !

**Comment by WheelyWonka** [comment]
Ok, found it. Just need to link manually Pods in xCode.

**Comment by HunterMeyer** [comment]
@WheelyWonka I'm having the same issue. Pretty new to Xcode myself. Can you explain how you manually linked Pods in Xcode?

**Comment by HunterMeyer** [comment]
O, I see. You go to into the projects General > Linked Frameworks and Libraries section. Click the + icon and add the .a files...

**Comment by WheelyWonka** [comment]
@HunterMeyer You can do it by going down to the General tab of your project "Linked frameworks and libraries" and add /ios/Pods.

**Comment by HunterMeyer** [comment]
@WheelyWonka thanks. I've added the ios/Pods directory to the "Linked frameworks and libraries" section. However, build is failing:
```
Warning: skipping file '/my/path/pepperoni-app-kit/ios/Pods' (unexpected file type 'folder' in Frameworks & Libraries build phase)
```

Am I doing something wrong? Feels like I've misses something. Thanks for the help.

**Comment by HunterMeyer** [comment]
Ok I figured it out. I was incorrectly opening the `.xcodeproj` file. Instead, I should be opening the `.xcworkspace` file. All is good.
