### ISSUE TITLE
Requiring unknown module "../../env"

### ISSUE THREAD

**Issue by sudharsan1988** [futurice/pepperoni-app-kit#56]
Running on Android(5.0) physical device, React-Native(0.26), npm(3.6.0), Windows -7. I am able to deploy the debug apk to physical device but getting the below error,

Requiring unknown module "../../env". If you are sure the module is there, try restarting the packager or running npm install.

I did both but keep on getting the same error. Any idea, what is causing this error?

**Comment by skyride99** [comment]
Getting the same error but with NPM 3.9 on Mac OS X

**Comment by jevakallio** [comment]
@sudharsan1988 @skyride99 have you followed the [Setup guide](https://github.com/futurice/pepperoni-app-kit/blob/master/docs/SETUP.md), specifically the following:
```
$ npm install
$ cp env.example.js env.js
```

**Comment by jevakallio** [comment]
@sudharsan1988, additionally we have not tested anything on Windows machines. We don't plan to support Windows as a first-class development environment until React Native does so itself, so any Windows-related issues might be better served by submitting issues to the react-native repository.

**Comment by skyride99** [comment]
Yes that is working.
