### ISSUE TITLE
Is it possible to integrate react-native-web with this?

### ISSUE THREAD

**Issue by elirov** [futurice/pepperoni-app-kit#62]

**Comment by jevakallio** [comment]
Yes, I'm sure that it is! Are you asking if we would include it in Pepperoni, or asking how to do it yourself?

**Comment by elirov** [comment]
I tried adding react-native-web to a bunch of react-native starter kits with no luck.  I was hoping there would be a **really** **simple** react-native/react-native-web starter kit that allows one to write a single code-base app and test it using react-native-web, and easily push out android/ios apps from that same project...

**Comment by jevakallio** [comment]
How about https://github.com/grabcode/react-native-web-starter ?

**Comment by elirov** [comment]
I love that kit, but it doesn't have the android and ios stuff in it, and I just can't seem to figure out how to integrate them into that framework.  I thought it might be easier to add the react-native-web stuff to a react-native-ios/android starter kit, but that's not really working for me either.  I'm just not that good at webpack yet... :)  I was just hoping someone would put together a simple starter kit that just works and has all three (android, ios, web) in one place as a starting off point.

**Comment by jevakallio** [comment]
I don't think we want to take react-native-web as a dependency. It would be a cool feature, but it also adds a lot of maintenance overhead and complexity, and at the same time it's bit of a niche requirement - most people won't use it.

Thanks for the suggestion, and good luck on your search!
