### ISSUE TITLE
Reload in Windows

### ISSUE THREAD

**Issue by Thomsos** [futurice/pepperoni-app-kit#63]
The docs assume OSX, how can I do this in Windows?

**Comment by jevakallio** [comment]
@Thomsos I don't know, none of our team has a Windows setup to test this with - which bit of the docs do you mean?

**Comment by tino-junge** [comment]
Closing this due inactivity. You can find general info on how to use the debug menu for React Native under Windows here: https://github.com/ReactWindows/react-native-windows#showing-the-debug-menu
