### ISSUE TITLE
Unfortunatelly, PepperoniAppTemplate has stopped

### ISSUE THREAD

**Issue by cciszak** [futurice/pepperoni-app-kit#69]
Get error message while starting vanila project 1.0.0 on android. Please find attached. The app also complain about env component.

Any Ideas? 

![screen shot 2016-07-03 at 02 03 28](https://cloud.githubusercontent.com/assets/11364221/16543223/67843d3c-40c2-11e6-812d-afbb67988097.png)

**Comment by gaykov** [comment]
Take a look at installation instuctions here: https://github.com/futurice/pepperoni-app-kit/blob/master/docs/SETUP.md#installation. You have to create a blank env file.

**Comment by cciszak** [comment]
Worked! Thanks!

**Comment by jevakallio** [comment]
We'll improve the visibility of the setup instructions in the docs. Thanks for your help on responding to this fast @gaykov!
