### ISSUE TITLE
Drop semicolons

### ISSUE THREAD

**Issue by jhabdas** [futurice/pepperoni-app-kit#70]
Since this kit gives opinion on linting rules and is becoming fairly popular I'm curious if you'd entertain a PR to drop the [semicolons](http://eslint.org/docs/rules/semi) (a fixable rule using `--fix`)? JS is easier to read and write without semicolons.

**Comment by jevakallio** [comment]
No thanks, but feel free to do so in your own project!

**Comment by jhabdas** [comment]
That's too bad. If you have a chance give it a shot sometime. I promise you'll never go back.
