### ISSUE TITLE
Firebase Authentication Blocked by Fork

### ISSUE THREAD

**Issue by jhabdas** [futurice/pepperoni-app-kit#71]
First off, loving the kit so far. I noticed it [forks `react-native-lock`](https://github.com/futurice/pepperoni-app-kit/blob/75a7b010e60896362f7c347eaf2d0f175a74633a/package.json#L40) and is currently 56 commits behind `auth0:master`. I'm already feeling the pain as the fork has [a bug preventing use of Auth0 delegation to the Firebase API](https://github.com/auth0/react-native-lock/issues/39), which was [fixed in the upstream master](https://github.com/auth0/react-native-lock/pull/45) and released to NPM.

Are there any immediate plans to update the fork or (ideally) stop forking?

**Comment by jevakallio** [comment]
Yes, let's get the fork up to date!

As long as the lock component [doesn't support UI customization](https://github.com/auth0/react-native-lock/pull/14#issuecomment-183031703) we intend to keep forking this repo.

**Comment by jevakallio** [comment]
I've rebased the https://github.com/futurice/react-native-lock/tree/feature/customizedTheme branch from upstream master.

@jhabdas could you re-run `npm install` in your app and verify that everything still works for you? It does for me.

**Comment by jhabdas** [comment]
On it

**Comment by jhabdas** [comment]
LGTM. Thanks for the update!
