### ISSUE TITLE
Awesome kit! Some questions..

### ISSUE THREAD

**Issue by michaelswe** [futurice/pepperoni-app-kit#73]
I'm new to React-Native and I've spent the last couple of weeks on reading up and testing stuff. Everything is awesome, except there is no "best practice" to find anywhere. I'm struggling to find my own way of organizing files, organizing Redux, Navigate between views, etc. 

Pepperoni with it's nice documentation gives me a great foundation and best practice. I like almost everything (Redux, Ducks, Coding style, etc), but maybe not Immutable.js. I'll give Immutable a good try though.

I have a couple of concerns:
**1. Local storage and memory consumption of Redux Store.**
Since AsyncStorage is used to save the complete state of the app as one big blob, there is no way to load the initial state (i.e. last snapshot) in a prioritized order. I was about to use SQLite or something for local storage, since I'll have a lot of data in the app.

- How much data is reasonable to have in the Redux State? Should I throw out old data after a while and force the app to refetch this from the server when/if it's needed again?
- I'll have a lot of image files in my app. Those are synced with the server and lives as files on the device local disk. My plan is to reference those files from the Redux State as kind of foreign keys (UUID). I'm thinking of having a separate slice in the state for images, but only for metadata such as isLoaded, etc. Does this make sense?

**2. Upgrading**
I assume/hope that Pepperoni will continue to evolve. What is the preferred concept of upgrading apps based on Pepperoni? 
- Are there distinct places/files in Pepperoni which could be upgraded? 
- Or would upgrading take a large amount of diff checking and merging?

**3. dependencies**
`pod install` got me a bunch of Cocoa Pods. Where are those used in Pepperoni? I have never used pods before. Are there similar Android "pods" available, or will these pods make the app single-platform?

**Comment by jhabdas** [comment]
@michaelswe There are some simple methods for ensuring state isn't mutated without using `Immutable.js`. My preference being implicit use of `Object.assign` by using ES7 Object Spread as described by Dan Abramov in [Getting Started With Redux](https://egghead.io/courses/getting-started-with-redux). I for one would eagerly like to see Immutable removed in favor of unit testing to ensure stat hasn't changed as Abramov explains in his video tutorials.

**Comment by jevakallio** [comment]
@michaelswe thanks for your interest and questions. Here's short answers:

1. How much data is too much? It's too much once it starts to have negative consequences, I suppose - either for the memory consumption of the app, or the startup time when rehydrating the state. 

The serialization setup we use has been more than adequate for all the apps that we've built, but it won't scale indefinitely. We have implemented cache pruning on startup (we use Immutable records and add a creation timestamp to all record instances, and only rehydrate records fresher than *n* days). It works well and would love to open source this as part of Pepperoni, but the IP belongs to one of our customers, so we need to implement that from scratch.

At some point, you may want to look at a database like SQLite or [Realm](https://realm.io/docs/react-native/latest/).

2. Upgrading is discussed at https://github.com/futurice/pepperoni-app-kit/issues/68

3. CocoaPods is a package manager for iOS, similar to what `npm` is for node and gems are for Ruby. Some React Native dependencies can be managed with former `rnpm` (now included in react-native core), but other package vendors choose to use platform-specific tools. In our case, the [Auth0](https://github.com/auth0/react-native-lock) component requires use of CocoaPods.

CocoaPods is a huge PITA, but it will be useful for any non-trivial app that targets iOS, so we chose to include it in Pepperoni.

It doesn't make the app single-platform, it simply manages and links the iOS-specific libraries and SDKs. If you use some native iOS library to achieve a certain functionality on iOS, you'll need to obviously implement the same functionality in Android yourself.

**Comment by michaelswe** [comment]
Thank you!
I'm not using Auth0, which means I'll have no Pod dependence for now.

Right now I'm trying to wrap my mind around the routing. I guess most of the logic around this will be found in NavigatorExperimental? I don't know if I should post my routing questions here or maybe try on Reactiflux.

**Comment by jevakallio** [comment]
We are not fully satisfied with the routing system we have in place - tracking work on that in https://github.com/futurice/pepperoni-app-kit/issues/51.

Reactiflux is better for general React Native issues as we currently have very limited time to provide support here, and our implementation is only a very thin abstraction over the NavigationExperimental anyways.

Closing this issue now, if you have any more specific Pepperoni-related questions, feel free to open new issues, or as you said yourself, turn to the Reactiflux community.
