### ISSUE TITLE
Required prop onNavigate

### ISSUE THREAD

**Issue by michaelswe** [futurice/pepperoni-app-kit#79]
I just pulled a new version of Pepperoni (b49d6db) into my project. Some problems/questions arose.

1. onNavigate is replaced by onNavigateBack, but NavigationCard and NavigationAnimatedView seems to need onNavigate as per their required props. Should I ignore this for now?

2. I just upgraded Flow to 0.28. Pulling from Pepperoni put the .flowconfig back to 0.27. Any reason for this? Should I stick with 0.27?

Thank you all for giving me a flying start with my app!

**Comment by jevakallio** [comment]
@michaelswe the `onNavigate` [required prop is removed](https://github.com/futurice/pepperoni-app-kit/blob/master/src/modules/navigation/NavigationView.js#L14-L18) - perhaps something went wrong with your merge?

Regarding `.flowconfig`, that's the latest version provided by the React Native 0.29 project template. I am personally not a flow user, so I can't say if there are any version incompatibility issues. If you are using newer flow and that works with React Native, feel free to keep your existing config.

**Comment by michaelswe** [comment]
Thanks.
I'm now closing my issue in shame.. I forgot `npm install` to get RN 0.29..
