### ISSUE TITLE
File structure advice

### ISSUE THREAD

**Issue by michaelswe** [futurice/pepperoni-app-kit#80]
I need three different screens that are related to the domain "project". The screens are:
- ProjectList (whole screen is a list)
- Project (screen shows a single project)
- ProjectCompact (half top of the screen shows project info, bottom half shows list of connected detail.

Would you throw all of these screens in the same module folder, i.e. "project"? In that case, should I merge the state handling into one single file, but have the views and viewcontainers as separate files?

I know there are endless discussions of folder structure at various forums. I like the Pepperoni structure best (Ducks, domain centric, decoupled) and I'd really like to follow a "Pepperoni best practice" if there is one.

**Comment by jhabdas** [comment]
@michaelswe Generally boilerplates and apps will provide a "File Structure" section in the `README` to help answer this question. Assuming those components you're looking to create are connected I believe they'd land in the `modules` folder, perhaps something like this:

`/src/modules/project/Projects`
`/src/modules/project/ProjectDetail`
`/src/modules/project/ProjectCompact`

In engineering practice the term _modules_ has always been overloaded. In the RN landscape _modules_, for example, could easily be conflated with [native modules](https://facebook.github.io/react-native/docs/native-modules-ios.html). Though in the context of this kit I believe they're intended to indicate components which contain code to connect to the Redux store.

My advice is to hit Medium. Over the last year I've seen some great discussion about how to structure projects. Unfortunately there is to correct structure, so my advice is to choose what works best for you and be consistent.

**Comment by michaelswe** [comment]
Thank you @jhabdas. I'll take your advice and head over to Medium. I'll also group my related screens in to "modules". This seems to be a good thing to do. 

Closing this now as it's not really an issue.
