### ISSUE TITLE
Starting guide

### ISSUE THREAD

**Issue by shargon** [futurice/pepperoni-app-kit#91]
Please , write starting guide for replace the Auth0 for custom auth by API rest

**Comment by jevakallio** [comment]
Thanks, this is on the roadmap. I made some initial notes about custom backend login functionality at https://github.com/futurice/pepperoni-app-kit/issues/92#issuecomment-238091047. 

This will be fleshed out, and we are considering providing a Auth0-less build out of the box. I'll close this issue now, thanks for the suggestion! 👍
