### ISSUE TITLE
setAuthenticationToken not used

### ISSUE THREAD

**Issue by fabriziomoscon** [futurice/pepperoni-app-kit#92]
hey @jevakallio I am using the `api.js` utility and I think it is very well written. Good job.
I am also using the `authentication.js`  utility, and I notice that `setAuthenticationToken` is not used. Is there any plan to integrate it?

**Comment by jevakallio** [comment]
Yes. We are (sloooowly) working on a companion Pepperoni backend solution, and we'll release an example authentication solution with that. Unfortunately I don't have a release date on that yet.

The mechanism is very simple, standard JSON Web Token (JWT)-based authentication that works as follows:

### If using Auth0
You can use the authentication token received from the Auth0 login (stored in state at `navigation.authenticationToken.accessToken` by calling `authentication.setAuthenticationToken('Bearer ' + token)`. After this the bearer token is sent on every request made through the Pepperoni API module.

Your server needs to then implement a middleware (or other method) that either [decodes the JWT using one of the methods documented here](https://auth0.com/docs/jwt) on each request, or forwards that token to the Auth0 `/tokeninfo` API [as documented here](https://auth0.com/docs/api/authentication).

### If not using Auth0

You need to implement JWT authentication on your backend. Low-effort solutions exist for all major web application servers. Normally this would involve creating a `/login` route that accepts authentication credentials (e.g. username and password) and returns an `Authorization` header with a bearer token.

In your application code, you can then do something like:
```
const response = await api.request('post', '/login', {username, password});
authentication.setAuthenticationToken(response.headers.get('authorization'));
```

Following this, all requests made through the API module will send this authorization header, and your backend middleware can decode the JWT and authenticate the user.

**Comment by tino-junge** [comment]
Auth0 has been removed so closing this issue here now
