### ISSUE TITLE
Showing navigation header depending on scene

### ISSUE THREAD

**Issue by zachrnolan** [futurice/pepperoni-app-kit#93]
I'm trying to hide the navigation header on certain screens. I see that there is a `shouldRenderHeader` prop I can pass into the NavigationTabView, but I can't seem to connect that with a specific scene. 

What's the best way to implement this?

**Comment by fabriziomoscon** [comment]
Hi, you are right it doesn't seem to be wired up with `NavigationView`
https://github.com/futurice/pepperoni-app-kit/blob/master/src/modules/navigation/NavigationView.js#L26-L31
the best way to implement it would be to add it to the navigation state:
https://github.com/futurice/pepperoni-app-kit/blob/master/src/modules/navigation/NavigationState.js#L35-L39
so you can specify a boolean for each initial scenes, and also you will need to pass a parameter when pushing new routes:
https://github.com/futurice/pepperoni-app-kit/blob/master/src/modules/counter/CounterView.js#L30

Also note that as `ReactNative` is migrating to using `NavigationExperimental` and consequently there is a PR to modify how the navigation work which doesn't allow you to hide the Header Title:
https://github.com/futurice/pepperoni-app-kit/pull/89 which still needs to be reviewed and merged (albeit I am already using it)

**Comment by zachrnolan** [comment]
Thanks @fabriziomoscon, I came to the same conclusions as you.

The one thing I can't figure out at the moment is how to retrieve the boolean parameter from the route push and send it to the Navigation.

```
<NavigationTabView
            router={AppRouter}
            navigationState={tabState}
            onNavigateBack={this.props.onNavigateBack}
            onNavigateCompleted={this.props.onNavigateCompleted}
            shouldRenderHeader={code that gets the current route shouldRenderHeader boolean value}
          />
```

I'm adding to the route push like so:

`this.props.dispatch(NavigationState.pushRoute({key: 'MediaDetail', title: rowData, shouldRenderHeader: true}))`

Any help is greatly appreciated.

**Comment by fabriziomoscon** [comment]
If pushed correctly it should be added to `tabState`, try to debug that variable.

**Comment by jevakallio** [comment]
This is fixed by https://github.com/futurice/pepperoni-app-kit/commit/311b3de359187b47ed344cdd1a246a3b3e4bcaec. 

Each route now requires `title` property, which is displayed in the navigation bar.

See comments in for more details https://github.com/futurice/pepperoni-app-kit/pull/89.
