### ISSUE TITLE
Make Auth0 an optional dependency

### ISSUE THREAD

**Issue by jevakallio** [futurice/pepperoni-app-kit#96]
I seems we have quite a lot of users who, understandably, do not want to use Auth0 for their authentication, https://github.com/futurice/pepperoni-app-kit/issues/78, https://github.com/futurice/pepperoni-app-kit/issues/91 among others.

We shipped Pepperoni with the assumption that it would be easier for the users to remove Auth0 than it would be to add it, but this assumption has turned out to be incorrect. Additionally, integrating Auth0 has become a lot easier due to `rnpm` now shipping with React Native.

Let's start work on downgrading Auth0 from a default dependency to an optional one, implemented as sample code and documentation.

**Comment by chadrien** [comment]
@jevakallio Regarding docs, does pointing to the code back when auth0 was still around be enough for you?

Something like this:

---

# Auth0

Pepperoni used to be bundled with [Auth0](https://auth0.com/) but it has been removed by popular request.

You can follow this guide to get it back.

## Installation

First, get the `react-native-lock` npm package.

```bash
$ npm i -S react-native-lock@futurice/react-native-lock#feature/customizedTheme
```

Then link the package to IOS and Android builds with the `link` command:

```bash
$ react-native link react-native-lock
```

## Usage

You can see exemple of code used in Pepperoni when Auth0 was still bundled [here](549fd09e).

The files you'll be interrested in are:

* [`src/modules/auth/AuthState.js`](https://github.com/futurice/pepperoni-app-kit/blob/549fd09ef153b4908a5a56482b81dbea7dc7fb2f/src/modules/auth/AuthState.js) (and [`src/modules/auth/__specs__/AuthState.spec.js`](https://github.com/futurice/pepperoni-app-kit/blob/549fd09ef153b4908a5a56482b81dbea7dc7fb2f/src/modules/auth/__specs__/AuthState.spec.js))
* [`src/services/auth0.js`](https://github.com/futurice/pepperoni-app-kit/blob/549fd09ef153b4908a5a56482b81dbea7dc7fb2f/src/services/auth0.js)
* [`src/redux/reducer.js`](https://github.com/futurice/pepperoni-app-kit/blob/549fd09ef153b4908a5a56482b81dbea7dc7fb2f/src/redux/reducer.js#L10)
* [`src/components/DeveloperMenu.android.js`](https://github.com/futurice/pepperoni-app-kit/blob/549fd09ef153b4908a5a56482b81dbea7dc7fb2f/src/components/DeveloperMenu.android.js#L33)
* [`src/components/DeveloperMenu.ios.js`](https://github.com/futurice/pepperoni-app-kit/blob/549fd09ef153b4908a5a56482b81dbea7dc7fb2f/src/components/DeveloperMenu.ios.js#L31)
* [`src/modules/AppView.js`](https://github.com/futurice/pepperoni-app-kit/blob/549fd09ef153b4908a5a56482b81dbea7dc7fb2f/src/modules/AppView.js#L33)
* [`src/modules/AppViewContainer.js`](https://github.com/futurice/pepperoni-app-kit/blob/549fd09ef153b4908a5a56482b81dbea7dc7fb2f/src/modules/AppViewContainer.js#L6-L7)
* [`src/modules/counter/CounterViewContainer.js`](https://github.com/futurice/pepperoni-app-kit/blob/549fd09ef153b4908a5a56482b81dbea7dc7fb2f/src/modules/counter/CounterViewContainer.js#L8-L9)
