### ISSUE TITLE
Snapshot Partially

### ISSUE THREAD

**Issue by Shamilik** [futurice/pepperoni-app-kit#98]
Is there any way to make partial snapshot? Without tabs for example..

**Comment by jevakallio** [comment]
Hi,

In [snapshot.js](https://github.com/futurice/pepperoni-app-kit/blob/master/src/utils/snapshot.js#L15), you can just modify the state before it is persisted. If you want to not persist the navigation state, you can do something like:
```
export async function saveSnapshot(state) {
  await persist(state.delete('navigationState').toJS());
}
```

**Comment by Shamilik** [comment]
Thanks you!

**Comment by arthurnn** [comment]
This caused me issues, where i change the tabs name, and old apps would still have the old content.
I wonder why you would want to persist the navigation state at all, if that does not come from an API or web request.
