### ISSUE TITLE
Plain objects in state get serialized and rehydrated as ImmutableJS structures

### ISSUE THREAD

**Issue by tehmou** [futurice/pepperoni-app-kit#99]
- If one adds plain JS objects in the state the app breaks on reload
- Probably we should enforce immutable objects to avoid confusion

**Comment by jevakallio** [comment]
@tehmou thanks for reporting this! I submitted a fix, can you see if that fixes your issue>

**Comment by jevakallio** [comment]
Okay, I can now see that https://github.com/futurice/pepperoni-app-kit/issues/100 isn't a sufficient fix for this.
